---
# tasks file for launch_2zone_vpc
- name: Create vpc {{ ec2_name_prefix }}-vpc
  ec2_vpc_net:
    name: "{{ ec2_name_prefix }}-vpc"
    cidr_block: "{{ ec2_subnet }}"
    region: "{{ ec2_region }}"
  register: create_vpc
  until: create_vpc is not failed
  retries: 5

- name: Set security group rules template
- set_fact:
    from_template: "{{ lookup('template', 'vpc_rules.j2') }}"

- name: Create security group {{ ec2_name_prefix }}-sg
  ec2_group:
    name: "{{ ec2_name_prefix }}-sg"
    description: "{{ ec2_name_prefix }}-sg"
    vpc_id: "{{ create_vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    rules: "{{ from_template.all_rules }}"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: ec2_vpc_id is undefined
  register: create_sg
  until: create_sg is not failed
  retries: 5

- name: Create subnet for {{ ec2_name_prefix }}-vpc
  ec2_vpc_subnet:
    region: "{{ ec2_region }}"
    az: "{{ item.az }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    cidr: "{{ item.cidr }}"
    wait_timeout: 600
    map_public: yes
    tags: "{{ item.tags }}"
  with_items: "{{ vpc_subnets }}"
  register: create_subnet
  when: ec2_vpc_id is undefined
  until: create_subnet is not failed
  retries: 15

- name: Get subnet ids
  set_fact:
    subnet_ids: "{{ create_subnet.results
      | selectattr('subnet.id', 'defined')
      | map(attribute='subnet.id')
      | list
      | unique }}"

- name: Create igw {{ ec2_name_prefix }}-igw
  ec2_vpc_igw:
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    tags:
      Name: "{{ ec2_name_prefix }}-igw"
      Demonstration: "{{ ec2_name_prefix }}"
  register: create_igw
  until: create_igw is not failed
  retries: 15

- name: Create rtb {{ ec2_name_prefix }}-rtb
  ec2_vpc_route_table:
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    subnets: "{{ subnet_ids }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ create_igw.gateway_id }}"
    tags:
      Name: "{{ ec2_name_prefix }}-rtb"
  register: create_rtb
  until: create_rtb is not failed
  retries: 5

- name: Show VPC components created
  debug:
    msg:
      - "ec2_name_prefix: {{ ec2_name_prefix }}"
      - "ec2 vpc id: {{ create_vpc.vpc.id }}"
      - "ec2 sg id: {{ create_sg.group_id }}"
      - "ec2 vpc subnet ids: {{ subnet_ids }}"
      - "ec2 igw id: {{ create_igw.gateway_id }}"
      - "ec2 rtb id: {{ create_rtb.route_table.route_table_id }}"
 